[tools]
node = "24"
elm = "0.19.1"

[tasks.lint]
run = "npm run format"

[tasks."build:css"]
run = "npm run css"

[tasks."build:compile"]
run = "npm run compile"

[tasks.build]
depends = ["lint", "build:*"]

[tasks.test]
run = "npm run test"

[tasks.dev]
depends = ["build", "test"]

[tasks.serve]
run = "npm run serve"
